// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]
use crate::schema::{subscription_tokens, users};

use chrono::offset::Utc;
use chrono::DateTime;
use diesel::{Identifiable, Queryable};
use serde::Deserialize;
use uuid::Uuid;

#[derive(Queryable, Debug, Identifiable, Deserialize)]
#[diesel(primary_key(subscription_token))]
pub struct SubscriptionToken {
    pub subscription_token: String,
    pub subscriber_id: Uuid,
}

#[derive(Queryable, Debug, Deserialize)]
pub struct Subscription {
    pub id: Uuid,
    pub email: String,
    pub name: String,
    pub subscribed_at: DateTime<Utc>,
    pub status: Option<String>,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(user_id))]
pub struct User {
    pub user_id: Uuid,
    pub username: String,
    pub password_hash: String,
}
